### ISSUE TITLE
"The content of app.json is not a valid JSON object." error shown when deployed on Heroku

### ISSUE THREAD

**Issue by grassland-curing-cfa** [cherukumilli/parse-dashboard-example#3]
Hi Diwakar,

I tried to follow the Readme file and clicked the "Deploy to Heroku" button to deploy the Dashboard project to my Heroku. But the following error message was shown on Heroku:

**"The content of app.json is not a valid JSON object."**

Any idea? Thanks!

Cheers,

**Comment by cherukumilli** [comment]
@grassland-curing-cfa 
Thanks for the issue.
The JSON was malformed. I fixed it. Can you please try it now and let me know?

**Comment by grassland-curing-cfa** [comment]
Thanks. I tried it again. It seemed to be successfully deployed. But it took quite a long time to start up the app on Heroku the first time (probably 5 mins!)

Anyways. You have done nice work!

I also tried to modify the index.js file to allow user and password for access the dashboard. It worked fine.

Another thing: do you have any idea how to support multiple Parse apps on the fly (add more Parse apps by specifying Config Vars. in run-time) on the dashboard on Heroku.

**Comment by cherukumilli** [comment]
@grassland-curing-cfa 

I didn't quite understand what adding `on the fly` here means. If you are talking about adding it at runtime then I don't know.

If you are talking about adding it when the dashboard launches then you can do it in the following way : `you may already know this :)`

# parse-dashboard-example

### index.js file

```
...
...
var dashboard = new ParseDashboard({
  apps: [
    {
      appId: process.env.PROD_APP_ID || 'myProdAppId',
      masterKey: process.env.PROD_MASTER_KEY || 'myProdMasterKey',
      serverURL: process.env.PROD_SERVER_URL || 'https://my-prod-app.com/parse',
      appName: process.env.PROD_APP_NAME || 'My Production App',
      production: true,
      iconName: 'my-prod-icon.png',
    },
    {
      appId: process.env.DEV_APP_ID || '12345678-1234-1234-1234-123456789053',
      masterKey: process.env.DEV_MASTER_KEY || '12345678-9012-3456-7890-123456789C6C',
      serverURL: process.env.DEV_SERVER_URL || 'http://localhost:1337/parse', // Self-hosted Parse Server
      appName: process.env.DEV_APP_NAME || 'My Development',
      iconName: 'my-dev.png',
    },
  ],
  users: [
    {
      user: process.env.MY_DASHBOARD_USERID || 'my-dashboard-userid',
      pass: process.env.MY_DASHBOARD_PASSWORD || my-dashboard-password',
      apps: [
        {
          appId: process.env.PROD_APP_ID || 'myProdAppId',
        },
        {
          appId: process.env.DEV_APP_ID || '12345678-1234-1234-1234-123456789053',
        },
      ],
    },
    {
      user: 'user2',
      pass: 'pass2',
      apps: [
        {
          appId: 'my-staging-AppId1',
        },
        {
          appId: 'my-test-AppId2',
        },
      ],
    },
  ],
  iconsFolder: 'icons',
});

...
...
...
```

**Comment by grassland-curing-cfa** [comment]
Thanks @cherukumilli 
In your example for multiple apps as above, your referenced "process.env.APP_ID" to appId twice; so if it is set in the Heroku Settings' Config. Vars panel, would it be just one app that is launched eventually as the first app would be overridden by the second one?

**Comment by cherukumilli** [comment]
Good catch. That is a mistake. 
It should say `process.env.PROD_APP_ID`, `process.env.DEV_APP_ID`, etc...

I just corrected my notes above...Please take a look and see if it makes sense
