### ISSUE TITLE
Why it not working on Heroku?

### ISSUE THREAD

**Issue by kevinlee85** [cherukumilli/parse-dashboard-example#6]
I have cloned your demo, then update my owned appid, masterKey and serverURL fields, then it working well on my local computer.
I meaned I tried "npm start", then everything works well.

After that, I have deployed  the same code to Heroku.
It response me "unable to connect the server", my parse server was hosted by Heroku too.

Do you know the root cause?

**Comment by cherukumilli** [comment]
@kevinlee85 
can you please let me know how you installed the dashboard on heroku?
Did you use the button to depoloy?
or
Did you use the heroku toolbelt / cli commands to push your code to heroku?

**Comment by kevinlee85** [comment]
@cherukumilli I was using CLI git push my heroku. My Dashboard can login, but cannot connect to my Parse Server.

**Comment by kevinlee85** [comment]
That's same code which hosted by Heroku, then I can open Dashboard page, but the dashboard cannot connect to parse server.
![screen shot 2017-01-25 at 11 28 12 am](https://cloud.githubusercontent.com/assets/6616311/22276818/6466a2f8-e2f1-11e6-89eb-3cec2abd8ed0.png)

**Comment by kevinlee85** [comment]
That's my localhost Dashboard with same code which works well:
![screen shot 2017-01-25 at 11 29 40 am](https://cloud.githubusercontent.com/assets/6616311/22276860/9fb7b8a6-e2f1-11e6-83a7-1e0e0b0a8c74.png)

**Comment by kevinlee85** [comment]
Anything about Heroku, or about HTTP VS HTTPS?

**Comment by joaquin102** [comment]
I have the exactly same problem. It works locally but it doesn't on Heroku.

**Comment by cherukumilli** [comment]
@kevinlee85 @joaquin102 
I apologize for the delay. I just got to it today. 

**Good news:** 
I was able to recreate the problem. 

**Solution:**
Please change your `heroku` **SERVER_URL** environment variable from 
`http://propassional.herokuapp.com/parse`.
to
`https://propassional.herokuapp.com/parse`.

i.e. Please use a **HTTPS** URL for the `parse-server`.

Please let me know if this doesn't work.

I updated the instructions for deployment to Heroku: https://github.com/cherukumilli/parse-dashboard-example/blob/master/README.md#using-heroku-cli

Any feedback will be greatly appreciated.

**Comment by cherukumilli** [comment]
closing this issue as the documentation is updated with commit: https://github.com/cherukumilli/parse-dashboard-example/commit/756e5a85d22b9c51a4ec062f1eb97732fbe9f1de

**Comment by kevinlee85** [comment]
@cherukumilli Thank you. Your solution works on my side. Sorry for my late reply.
